class Translator
  attr_reader :rna, :parsed_seq, :parsed_arr

  def initialize(dna_seq = nil)
    @rna = Rna.new(dna_seq)
  end

  def translate
    @parsed_seq = @rna.rna_seq.gsub!(/(.{3})/, '\1 ')
    @parsed_seq.gsub!("AUG", "M")
    @parsed_seq.gsub!("AUC", "I")
    @parsed_seq.gsub!("AUU", "I")
    @parsed_seq.gsub!("AUA", "I")
    @parsed_seq.gsub!("ACU", "T")
    @parsed_seq.gsub!("ACC", "T")
    @parsed_seq.gsub!("ACA", "T")
    @parsed_seq.gsub!("ACG", "T")
    @parsed_seq.gsub!("AAU", "N")
    @parsed_seq.gsub!("AAC", "N")
    @parsed_seq.gsub!("AAA", "K")
    @parsed_seq.gsub!("AAG", "K")
    @parsed_seq.gsub!("AGU", "S")
    @parsed_seq.gsub!("AGC", "S")
    @parsed_seq.gsub!("AGA", "R")
    @parsed_seq.gsub!("AGG", "R")
    @parsed_seq.gsub!("GUU", "V")
    @parsed_seq.gsub!("GUC", "V")
    @parsed_seq.gsub!("GUA", "V")
    @parsed_seq.gsub!("GUG", "V")
    @parsed_seq.gsub!("GCU", "A")
    @parsed_seq.gsub!("GCC", "A")
    @parsed_seq.gsub!("GCA", "A")
    @parsed_seq.gsub!("GCG", "A")
    @parsed_seq.gsub!("GAU", "D")
    @parsed_seq.gsub!("GAC", "D")
    @parsed_seq.gsub!("GAA", "E")
    @parsed_seq.gsub!("GAG", "E")
    @parsed_seq.gsub!("GGU", "G")
    @parsed_seq.gsub!("GGC", "G")
    @parsed_seq.gsub!("GGA", "G")
    @parsed_seq.gsub!("GGG", "G")
    @parsed_seq.gsub!("UUU", "F")
    @parsed_seq.gsub!("UUC", "F")
    @parsed_seq.gsub!("UUA", "L")
    @parsed_seq.gsub!("UUG", "L")
    @parsed_seq.gsub!("UCU", "S")
    @parsed_seq.gsub!("UCC", "S")
    @parsed_seq.gsub!("UCA", "S")
    @parsed_seq.gsub!("UCG", "S")
    @parsed_seq.gsub!("UAU", "Y")
    @parsed_seq.gsub!("UAC", "Y")
    @parsed_seq.gsub!("UGU", "C")
    @parsed_seq.gsub!("UGC", "C")
    @parsed_seq.gsub!("UGG", "W")
    @parsed_seq.gsub!("CUU", "L")
    @parsed_seq.gsub!("CUC", "L")
    @parsed_seq.gsub!("CUA", "L")
    @parsed_seq.gsub!("CUG", "L")
    @parsed_seq.gsub!("CCU", "P")
    @parsed_seq.gsub!("CCC", "P")
    @parsed_seq.gsub!("CCA", "P")
    @parsed_seq.gsub!("CCG", "P")
    @parsed_seq.gsub!("CAU", "H")
    @parsed_seq.gsub!("CAC", "H")
    @parsed_seq.gsub!("CAA", "Q")
    @parsed_seq.gsub!("CAG", "Q")
    @parsed_seq.gsub!("CGU", "R")
    @parsed_seq.gsub!("CGC", "R")
    @parsed_seq.gsub!("CGA", "R")
    @parsed_seq.gsub!("CGG", "R")
    @parsed_seq.gsub!("UGA", "*")
    @parsed_seq.gsub!("UAA", "*")
    @parsed_seq.gsub!("UAG", "*")
  end
end
